---
title: "Earthworm Isoniche Analysis"
author: "Gen-Chang Hsu"
date: "3/1/2021"
output: html_document
---

<style type = "text/css">

  body{font-size: 14pt; }
  
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      error = FALSE,
                      warning = FALSE,
                      out.width = "100%")
```

# Data Preparation
```{r data_prep}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(readxl)


# Import files ------------------------------------------------------------
BiodiversiTREE_worm_raw <- read_xlsx("./data_raw/BiodiversiTREE_data.xlsx", sheet = 1)
BiodiversiTREE_soil_raw <- read_xlsx("./data_raw/BiodiversiTREE_data.xlsx", sheet = 2)
SERC_raw <- read_xlsx("./data_raw/SERC_data.xlsx", sheet = 1)
BARC_raw <- read_xlsx("./data_raw/BARC_data.xlsx", sheet = 1)


# Code starts here ---------------------------------------------------------

### BiodiversiTREE_1 (excluding Plot 39 and 40)
BiodiversiTREE_soil_clean1 <- BiodiversiTREE_soil_raw %>% 
  filter(!Plot %in% c(39, 40)) %>%
  select(Plot, Depth, ends_with(c("d13C", "d15N"))) %>%
  group_by(Plot, Depth) %>%
  summarise_all(.funs = mean) %>%
  rename("d13C_soil" = "Linear corr d13C",
         "d15N_soil" = "Linear corr d15N") %>%
  ungroup() %>%
  mutate(Depth = factor(Depth, levels = c("0-2", "2-5", "5-10", "10-20"), ordered = T)) %>%
  arrange(Plot, Depth)

BiodiversiTREE_worm_clean1 <- BiodiversiTREE_worm_raw %>% 
  filter(!Plot %in% c(39, 40)) %>%
  select(Plot, Species, ends_with(c("d13C", "d15N"))) %>%
  rename("d13C_worm" = "Linear corr d13C",
         "d15N_worm" = "Linear corr d15N") %>% 
  ungroup()

BiodiversiTREE_clean1 <- BiodiversiTREE_soil_clean1 %>% 
  filter(Depth %in% c("0-2", "2-5")) %>%
  group_by(Plot) %>%
  summarise_at(vars(ends_with("soil")), function(x){
    x[1]*0.4 + x[2]*0.6  # weighted mean by depth
  }) %>%
  right_join(BiodiversiTREE_worm_clean1, by = "Plot") %>%
  mutate(Dataset = "BiodiversiTREE_1") %>%
  mutate(Plot = as.character(Plot)) %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### BiodiversiTREE_2 (Plot 39 and 40)
BiodiversiTREE_soil_clean2 <- BiodiversiTREE_soil_raw %>% 
  filter(Plot %in% c(39, 40)) %>%
  select(Plot, Depth, ends_with(c("d13C", "d15N"))) %>%
  group_by(Plot, Depth) %>%
  summarise_all(.funs = mean) %>%
  rename("d13C_soil" = "Linear corr d13C",
         "d15N_soil" = "Linear corr d15N") %>%
  ungroup() %>%
  mutate(Depth = factor(Depth, levels = c("0-2", "2-5", "5-10", "10-20"), ordered = T)) %>%
  arrange(Plot, Depth)

BiodiversiTREE_worm_clean2 <- BiodiversiTREE_worm_raw %>% 
  filter(Plot %in% c(39, 40)) %>%
  select(Plot, Species, ends_with(c("d13C", "d15N"))) %>%
  rename("d13C_worm" = "Linear corr d13C",
         "d15N_worm" = "Linear corr d15N") %>% 
  ungroup()

BiodiversiTREE_clean2 <- BiodiversiTREE_soil_clean2 %>% 
  filter(Depth %in% c("0-2", "2-5")) %>%
  group_by(Plot) %>%
  summarise_at(vars(ends_with("soil")), function(x){
    x[1]*0.4 + x[2]*0.6  # weighted mean by depth
  }) %>%
  right_join(BiodiversiTREE_worm_clean2, by = "Plot") %>%
  mutate(Dataset = "BiodiversiTREE_2") %>%
  mutate(Plot = as.character(Plot)) %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### BARC
BARC_worm_clean <- BARC_raw %>% 
  filter(`sample type` == "earthworm") %>% 
  select(Plot = quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

BARC_soil_clean <- BARC_raw %>% 
  filter(`sample type` == "soil" & depth == "0_5") %>% 
  select(Plot = quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N)

BARC_clean <- BARC_worm_clean %>%
  left_join(BARC_soil_clean, by = "Plot") %>%
  mutate(Dataset = "BARC") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### SERC_2011
SERC_2011_worm_clean <- SERC_raw %>% 
  filter(Year == 2011 & `Sample _type` == "earthworm") %>% 
  select(Plot = Quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

SERC_2011_soil_clean <- SERC_raw %>% 
  filter(Year == 2011 & `Sample _type` == "soil" & Soil_depth == "0_5") %>% 
  select(Plot = Quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N) %>% 
  group_by(Plot) %>%
  summarise(d13C_soil = mean(d13C_soil), 
            d15N_soil = mean(d15N_soil))

SERC_2011_clean <- SERC_2011_worm_clean %>%
  left_join(SERC_2011_soil_clean, by = "Plot") %>%
  mutate(Dataset = "SERC_2011") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### SERC_2013
SERC_2013_worm_clean <- SERC_raw %>% 
  filter(Year == 2013 & `Sample _type` == "earthworm") %>% 
  select(Plot = Quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

SERC_2013_soil_clean <- SERC_raw %>% 
  filter(Year == 2013 & `Sample _type` == "soil" & Soil_depth == "0_5") %>% 
  select(Plot = Quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N) %>% 
  group_by(Plot) %>%
  summarise(d13C_soil = mean(d13C_soil), 
            d15N_soil = mean(d15N_soil))

SERC_2013_clean <- SERC_2013_worm_clean %>%
  left_join(SERC_2013_soil_clean, by = "Plot") %>%
  mutate(Dataset = "SERC_2013") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### Merge all datasets
all_data_clean <- bind_rows(BiodiversiTREE_clean1, 
                            BiodiversiTREE_clean2,
                            BARC_clean,
                            SERC_2011_clean,
                            SERC_2013_clean) %>%
  rename(d13C_soil_0_5 = d13C_soil,
         d15N_soil_0_5 = d15N_soil) %>%
  mutate(Species = plyr::mapvalues(Species, 
                             from = c("caliginosa", 
                                      "trapezoides",
                                      "cyaneum",
                                      "lonnbergi",               
                                      "rubellus",
                                      "terrestris",
                                      "hilgendorfi"), 
                             to = c("Aporrectodea caliginosa", 
                                    "Aporrectodea trapezoides",
                                    "Octolasion cyaneum",
                                    "Eisenoides lonnbergi",
                                    "Lumbricus rubellus",
                                    "Lumbricus terrestris",
                                    "Amynthas hilgendorfi")))

write_rds(all_data_clean, "./Output/Data_clean/all_data_clean.rds")

DT::datatable(all_data_clean)
```

<br>

# Isotope biplot
```{r BiodiversiTREE and BARC biplot, fig.width = 11, fig.height = 4.5}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(ggsci)


# Import files ------------------------------------------------------------
all_data_clean <- readRDS("./Output/Data_clean/all_data_clean.rds")


# ggplot2 theme -----------------------------------------------------------
mytheme <- theme(
      axis.text.x = element_text(size = 12, color = "black"),
      axis.text.y = element_text(size = 12, color = "black"),
      axis.title.x = element_text(size = 15, margin = margin(t = 10)),
      axis.title.y = element_text(size = 15, margin = margin(r = 5)),
      plot.title = element_text(hjust = 0.5, size = 18),
      plot.margin = margin(0.2, 0.05, 0.05, 0.05, "null"),
      panel.background = element_rect(fill = "transparent"),
      plot.background = element_rect(colour = "transparent"),
      panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
      panel.grid.major.x = element_blank(),
      panel.grid.minor.x = element_blank(),
      panel.grid.major.y = element_blank(),
      panel.grid.minor.y = element_blank(),
      strip.background = element_blank(),
      strip.text = element_text(size = 12),
      legend.spacing.x = unit(0.1, "cm"),
      legend.spacing.y = unit(0.15, "cm"),
      legend.key.width = unit(1.2, "cm"),
      legend.key.size = unit(1, "line"),
      legend.key = element_blank(),
      legend.text = element_text(size = 7),
      legend.text.align = 0,
      legend.box.just = "center",
      legend.justification = c(0.5, 0.5),
      legend.title.align = 0.5,
      legend.background = element_rect(fill = "transparent", size = 0.5, linetype = "solid", colour = "transparent"))
  

# Code starts here ---------------------------------------------------------

### Background-adjusted earthworm stable isotope values
adjusted_data <- all_data_clean %>%
  group_by(Dataset) %>%
  
  # Compute the differences between plot-level soil SI values and 
  # site-level (dataset-level) grand mean values (i.e., background references)
  mutate(d13C_soil_grand_mean = mean(d13C_soil_0_5),      
         d15N_soil_grand_mean = mean(d15N_soil_0_5)) %>%
  
  # Adjust the earthworm SI values by shifting back the differences between 
  # plot-level soil SI values and grand mean values 
  mutate(d13C_worm_adjusted = d13C_worm - (d13C_soil_0_5 - d13C_soil_grand_mean),
         d15N_worm_adjusted = d15N_worm - (d15N_soil_0_5 - d15N_soil_grand_mean)) %>%
  ungroup() %>%
  
  # Reorder the levels in column "Dataset" for plotting purpose
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))


### Stable isotope biplots for BiodiversiTREE and BARC datasets
label_df1 <- data.frame(Dataset = c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC"),
                       x = c(-33.5, -33.5, -33.5), 
                       y = c(13.25, 13.25, 13.25),
                       Label = c("(a)", "(b)", "(c)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

adjusted_data %>% 
  filter(Dataset %in% c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC")) %>%
  ggplot(aes(x = d13C_worm_adjusted, y = d15N_worm_adjusted)) +
  geom_point(aes(color = Species), size = 1.2, alpha = 0.7, stroke = 1) +
  labs(x = expression(paste(delta^{13}, "C (\u2030)", sep = "")), 
       y = expression(paste(delta^{15}, "N (\u2030)", sep = ""))) +
  
  # 50% data ellipse using a multivariate t-distribution
  stat_ellipse(aes(color = Species), type = "t", level = 0.5, size = 0.6) +
  facet_wrap(~Dataset, scales = "free_y") +
  geom_text(data = label_df1, aes(x = x, y = y, label = Label), size = 5) +
  scale_color_npg(name = NULL, 
                  label = c(expression(italic("Allolobophora chlorotica")),
                            expression(italic("Aporrectodea caliginosa")),
                            expression(italic("Aporrectodea trapezoides")),
                            expression(paste(italic("Diplocardia"), " sp.")),
                            expression(italic("Lumbricus friendi")),
                            expression(italic("Lumbricus rubellus")))) +
  coord_cartesian(xlim = c(-32, -13), ylim = c(0, 12), clip = "off") +
  scale_y_continuous(breaks = seq(1, 11, 2), labels = c("1.0", "3.0", "5.0", "7.0", "9.0", "11.0")) + 
  scale_x_continuous(breaks = seq(-30, -15, 5), labels = c("-30.0", "-25.0", "-20.0", "-15.0")) +
  guides(color = guide_legend(nrow = 2, byrow = T)) +
  mytheme + 
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 1.2)) 
  
ggsave("Output/Figures/Biplot1.tiff", width = 11, height = 4.5, dpi = 600)
```

```{r SERC biplot, fig.width = 8, fig.height = 4.5}
### Stable isotope biplots for SERC datasets
label_df2 <- data.frame(Dataset = c("SERC_2011", "SERC_2013"),
                       x = c(-33.5, -33.5), 
                       y = c(13.25, 13.25),
                       Label = c("(a)", "(b)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

adjusted_data %>% 
  filter(Dataset %in% c("SERC_2011", "SERC_2013")) %>%
  ggplot(aes(x = d13C_worm_adjusted, y = d15N_worm_adjusted)) +
  geom_point(aes(color = Species), size = 1.2, alpha = 0.7, stroke = 1) +
  labs(x = expression(paste(delta^{13}, "C (\u2030)", sep = "")), 
       y = expression(paste(delta^{15}, "N (\u2030)", sep = ""))) +
  
  # 50% data ellipse using a multivariate t-distribution
  stat_ellipse(aes(color = Species), type = "t", level = 0.5, size = 0.6) +
  facet_wrap(~Dataset, scales = "free_y") +
  geom_text(data = label_df2, aes(x = x, y = y, label = Label), size = 5) +
  scale_color_brewer(name = NULL, palette = "Set1",
                  label = c(expression(italic("Amynthas hilgendorfi")),
                            expression(italic("Aporrectodea caliginosa")),
                            expression(italic("Eisenoides lonnbergi")),
                            expression(italic("Lumbricus rubellus")),
                            expression(italic("Lumbricus terrestris")),
                            expression(italic("Octolasion cyaneum")))) +
  coord_cartesian(xlim = c(-35, -20), ylim = c(-3, 6), clip = "off") +
  scale_y_continuous(breaks = seq(-3, 6, 1.5), labels = c("-3.0", "-1.5", "0", "1.5", "3.0", "4.5", "6.0")) + 
  scale_x_continuous(breaks = seq(-35, -20, 3), labels = c("-35.0", "-32.0", "-29.0", "-26.0", "-23.0", "-20.0")) +
  guides(color = guide_legend(nrow = 2, byrow = T)) +
  mytheme + 
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 1.2)) 

ggsave("Output/Figures/Biplot2.tiff", width = 8, height = 4.5, dpi = 600)

```

<br>

# Isotopic niche analysis
1. Compute total area (TA), SEA, SEAc, and 95% ellipse area for each species
2. Compute overlap in SEA and 95% ellipse area between species pairs
3. PERMANOVA and PERMADISP to test the differences in species' isoniches
```{r isoniche}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(hdrcde)
library(vegan)
library(SIBER)


# Import files ------------------------------------------------------------
all_data_clean <- readRDS("./Output/Data_clean/all_data_clean.rds")


# Code start here ---------------------------------------------------------

### Background-adjusted earthworm stable isotope values
adjusted_data <- all_data_clean %>%
  group_by(Dataset) %>%
  
  # Compute the differences between plot-level soil SI values and 
  # site-level (dataset-level) grand mean values (i.e., background references)
  mutate(d13C_soil_grand_mean = mean(d13C_soil_0_5),      
         d15N_soil_grand_mean = mean(d15N_soil_0_5)) %>%
  
  # Adjust the earthworm SI values by shifting back the differences between 
  # plot-level soil SI values and grand mean values 
  mutate(d13C_worm_adjusted = d13C_worm - (d13C_soil_0_5 - d13C_soil_grand_mean),
         d15N_worm_adjusted = d15N_worm - (d15N_soil_0_5 - d15N_soil_grand_mean)) %>%
  ungroup() %>%
  
  # Reorder the levels in column "Dataset" for plotting purpose
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))


### Summary statistics of species isotopic niches by dataset

# A vector of the dataset names
dataset_list <- unique(as.character(adjusted_data$Dataset))

Isoniche_list <- lapply(dataset_list, function(dataset){
    
  set.seed(123)  # For PERMANOVA and PERMADISP
  
  # Create SIBER object
  SIBER_data <- adjusted_data %>% 
    filter(Dataset == dataset) %>%
    group_by(Species) %>%
    mutate(n.ind = n()) %>%
    filter(n.ind > 3) %>%
    select(iso1 = d13C_worm_adjusted, 
           iso2 = d15N_worm_adjusted,
           group = Species) %>%
    arrange(group) %>% 
    ungroup() %>%
    mutate(group = plyr::mapvalues(group, 
                                   unique(group), 
                                   1:length(unique(group)))) %>%
    mutate(community = 1) %>% 
    as.data.frame() %>% 
    createSiberObject()
  
  # Get the species names
  Sp_names <- adjusted_data %>% 
    filter(Dataset == dataset) %>%
    group_by(Species) %>%
    mutate(n.ind = n()) %>%
    filter(n.ind > 3) %>%
    .$Species %>% 
    unique() %>% 
    sort()
  
  # Total isoniche area and SEAc
  total_area <- groupMetricsML(SIBER_data) %>% 
    as.data.frame() %>%
    `names<-`(Sp_names) %>%
    t() %>% 
    as.data.frame() %>%
    rownames_to_column(var = "Species") %>%
    select(Species, TA, SEAc)
  
  # SEA overlap between species pairs
  SEA_overlap <- data.frame(
    Sp1 = rep(Sp_names, each = length(Sp_names)),
    Sp2 = rep(Sp_names),
    Ellipse1 = paste(1, rep(1:length(Sp_names), each = length(Sp_names)), sep = "."),
    Ellipse2 = paste(1, rep(1:length(Sp_names)), sep = ".")) %>%
    bind_cols(., map2(.x = .$Ellipse1, .y = .$Ellipse2, function(x, y) {
      maxLikOverlap(x, y, SIBER_data, p.interval = NULL, n = 100)
    }) %>% bind_rows()) %>%
    select(-Ellipse1, -Ellipse2, -area.2) %>%
    rename(SEA = area.1,
           Area = overlap) %>%
    mutate(Percent_overlap = Area/SEA) %>%
    filter(Sp1 != Sp2) %>%
    rename(Species = Sp1) %>%
    group_by(Species) %>%
    rename(SEA_overlap_with = Sp2) %>%
    nest(SEA_overlap = c(SEA_overlap_with, Area, Percent_overlap))
  
  # 95% ellipse area overlap between species pairs
  `95%_EA_overlap` <- data.frame(
    Sp1 = rep(Sp_names, each = length(Sp_names)),
    Sp2 = rep(Sp_names),
    Ellipse1 = paste(1, rep(1:length(Sp_names), each = length(Sp_names)), sep = "."),
    Ellipse2 = paste(1, rep(1:length(Sp_names)), sep = ".")) %>%
    bind_cols(., map2(.x = .$Ellipse1, .y = .$Ellipse2, function(x, y) {
      maxLikOverlap(x, y, SIBER_data, p.interval = 0.95, n = 100)
    }) %>% bind_rows()) %>%
    select(-Ellipse1, -Ellipse2, -area.2) %>%
    rename(`95%_EA` = area.1,
           Area = overlap) %>%
    mutate(Percent_overlap = Area/`95%_EA`) %>%
    filter(Sp1 != Sp2) %>%
    rename(Species = Sp1) %>%
    group_by(Species) %>%
    rename(`95%_EA_overlap_with` = Sp2) %>%
    nest(`95%_EA_overlap` = c(`95%_EA_overlap_with`, Area, Percent_overlap))
  
  # PERMANOVA and PERMADISP tests for multivariate differences in species isoniches
  PERM_tests <- data.frame(
    Sp1 = rep(Sp_names, each = length(Sp_names)),
    Sp2 = rep(Sp_names)) %>%
    select(Sp1, Sp2) %>%
    mutate(PERMANOVA_pval = map2(Sp1, Sp2, function(x, y){
      if (x == y){
        return(NA)
      } else {
        data = filter(filter(adjusted_data, Dataset == dataset), Species %in% c(x, y))
        PERMANOVA_out <- adonis(d15N_worm_adjusted + d13C_worm_adjusted ~ Species,
                                data = data,
                                method = "eu", 
                                permutations = 999)
        return(PERMANOVA_out$aov.tab$`Pr(>F)`[1])
      }
    })) %>%
    mutate(PERMADISP_pval = map2(Sp1, Sp2, function(x, y){
      if (x == y){
        return(NA)
      } else {
        data <- filter(filter(adjusted_data, Dataset == dataset), Species %in% c(x, y))
        Dist <- dist(data[, c("d15N_worm_adjusted", "d13C_worm_adjusted")])  
        PERMADISP_out <- betadisper(Dist, group = data$Species)
        PERMADISP_out_perm <- permutest(PERMADISP_out, pairwise = TRUE, permutations = 999)
        return(PERMADISP_out_perm$tab$`Pr(>F)`[1])
      }
    })) %>%
    filter(Sp1 != Sp2) %>%
    rename(Species = Sp1) %>%
    group_by(Species) %>%
    rename(Test_with = Sp2) %>%
    nest(PERM_tests = c(Test_with, PERMANOVA_pval, PERMADISP_pval))
  
  # Combine all the results
  niche_sum_stat <- total_area %>%
    left_join( SEA_overlap, by = "Species") %>%
    left_join(`95%_EA_overlap`, by = "Species") %>%
    left_join(PERM_tests, by = "Species")
  
  return(niche_sum_stat)
  
}) %>% 
  `names<-`(dataset_list)


### Convert the list into a dataframe
Isoniche_df <- Isoniche_list %>% 
  bind_rows(.id = "Dataset")

write_rds(Isoniche_df, "./Output/Data_clean/Isoniche.rds")

DT::datatable(unnest(Isoniche_df))
```

