---
title: "Bayesian Standard Ellipses Area"
author: "Gen-Chang Hsu"
date: "3/7/2021"
output: html_document
---

<style type = "text/css">

  body{font-size: 14pt; }
  
</style>

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      message = FALSE, 
                      error = FALSE,
                      warning = FALSE,
                      out.width = "100%")
set.seed(123)
```

# Data Preparation
```{r data_prep}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(readxl)


# Import files ------------------------------------------------------------
BiodiversiTREE_worm_raw <- read_xlsx("./data_raw/BiodiversiTREE_data.xlsx", sheet = 1)
BiodiversiTREE_soil_raw <- read_xlsx("./data_raw/BiodiversiTREE_data.xlsx", sheet = 2)
SERC_raw <- read_xlsx("./data_raw/SERC_data.xlsx", sheet = 1)
BARC_raw <- read_xlsx("./data_raw/BARC_data.xlsx", sheet = 1)


# Code starts here ---------------------------------------------------------

### BiodiversiTREE_1 (excluding Plot 39 and 40)
BiodiversiTREE_soil_clean1 <- BiodiversiTREE_soil_raw %>% 
  filter(!Plot %in% c(39, 40)) %>%
  select(Plot, Depth, ends_with(c("d13C", "d15N"))) %>%
  group_by(Plot, Depth) %>%
  summarise_all(.funs = mean) %>%
  rename("d13C_soil" = "Linear corr d13C",
         "d15N_soil" = "Linear corr d15N") %>%
  ungroup() %>%
  mutate(Depth = factor(Depth, levels = c("0-2", "2-5", "5-10", "10-20"), ordered = T)) %>%
  arrange(Plot, Depth)

BiodiversiTREE_worm_clean1 <- BiodiversiTREE_worm_raw %>% 
  filter(!Plot %in% c(39, 40)) %>%
  select(Plot, Species, ends_with(c("d13C", "d15N"))) %>%
  rename("d13C_worm" = "Linear corr d13C",
         "d15N_worm" = "Linear corr d15N") %>% 
  ungroup()

BiodiversiTREE_clean1 <- BiodiversiTREE_soil_clean1 %>% 
  filter(Depth %in% c("0-2", "2-5")) %>%
  group_by(Plot) %>%
  summarise_at(vars(ends_with("soil")), function(x){
    x[1]*0.4 + x[2]*0.6  # weighted mean by depth
  }) %>%
  right_join(BiodiversiTREE_worm_clean1, by = "Plot") %>%
  mutate(Dataset = "BiodiversiTREE_1") %>%
  mutate(Plot = as.character(Plot)) %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### BiodiversiTREE_2 (Plot 39 and 40)
BiodiversiTREE_soil_clean2 <- BiodiversiTREE_soil_raw %>% 
  filter(Plot %in% c(39, 40)) %>%
  select(Plot, Depth, ends_with(c("d13C", "d15N"))) %>%
  group_by(Plot, Depth) %>%
  summarise_all(.funs = mean) %>%
  rename("d13C_soil" = "Linear corr d13C",
         "d15N_soil" = "Linear corr d15N") %>%
  ungroup() %>%
  mutate(Depth = factor(Depth, levels = c("0-2", "2-5", "5-10", "10-20"), ordered = T)) %>%
  arrange(Plot, Depth)

BiodiversiTREE_worm_clean2 <- BiodiversiTREE_worm_raw %>% 
  filter(Plot %in% c(39, 40)) %>%
  select(Plot, Species, ends_with(c("d13C", "d15N"))) %>%
  rename("d13C_worm" = "Linear corr d13C",
         "d15N_worm" = "Linear corr d15N") %>% 
  ungroup()

BiodiversiTREE_clean2 <- BiodiversiTREE_soil_clean2 %>% 
  filter(Depth %in% c("0-2", "2-5")) %>%
  group_by(Plot) %>%
  summarise_at(vars(ends_with("soil")), function(x){
    x[1]*0.4 + x[2]*0.6  # weighted mean by depth
  }) %>%
  right_join(BiodiversiTREE_worm_clean2, by = "Plot") %>%
  mutate(Dataset = "BiodiversiTREE_2") %>%
  mutate(Plot = as.character(Plot)) %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### BARC
BARC_worm_clean <- BARC_raw %>% 
  filter(`sample type` == "earthworm") %>% 
  select(Plot = quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

BARC_soil_clean <- BARC_raw %>% 
  filter(`sample type` == "soil" & depth == "0_5") %>% 
  select(Plot = quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N)

BARC_clean <- BARC_worm_clean %>%
  left_join(BARC_soil_clean, by = "Plot") %>%
  mutate(Dataset = "BARC") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### SERC_2011
SERC_2011_worm_clean <- SERC_raw %>% 
  filter(Year == 2011 & `Sample _type` == "earthworm") %>% 
  select(Plot = Quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

SERC_2011_soil_clean <- SERC_raw %>% 
  filter(Year == 2011 & `Sample _type` == "soil" & Soil_depth == "0_5") %>% 
  select(Plot = Quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N) %>% 
  group_by(Plot) %>%
  summarise(d13C_soil = mean(d13C_soil), 
            d15N_soil = mean(d15N_soil))

SERC_2011_clean <- SERC_2011_worm_clean %>%
  left_join(SERC_2011_soil_clean, by = "Plot") %>%
  mutate(Dataset = "SERC_2011") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### SERC_2013
SERC_2013_worm_clean <- SERC_raw %>% 
  filter(Year == 2013 & `Sample _type` == "earthworm") %>% 
  select(Plot = Quadret, 
         Species = species, 
         d13C_worm = d13C, 
         d15N_worm = d15N)

SERC_2013_soil_clean <- SERC_raw %>% 
  filter(Year == 2013 & `Sample _type` == "soil" & Soil_depth == "0_5") %>% 
  select(Plot = Quadret, 
         d13C_soil = d13C, 
         d15N_soil = d15N) %>% 
  group_by(Plot) %>%
  summarise(d13C_soil = mean(d13C_soil), 
            d15N_soil = mean(d15N_soil))

SERC_2013_clean <- SERC_2013_worm_clean %>%
  left_join(SERC_2013_soil_clean, by = "Plot") %>%
  mutate(Dataset = "SERC_2013") %>%
  select(Dataset, Plot, Species, d13C_worm, d15N_worm, d13C_soil, d15N_soil)


### Merge all datasets
all_data_clean <- bind_rows(BiodiversiTREE_clean1, 
                            BiodiversiTREE_clean2,
                            BARC_clean,
                            SERC_2011_clean,
                            SERC_2013_clean) %>%
  rename(d13C_soil_0_5 = d13C_soil,
         d15N_soil_0_5 = d15N_soil) %>%
  mutate(Species = plyr::mapvalues(Species, 
                             from = c("caliginosa", 
                                      "trapezoides",
                                      "cyaneum",
                                      "lonnbergi",               
                                      "rubellus",
                                      "terrestris",
                                      "hilgendorfi"), 
                             to = c("Aporrectodea caliginosa", 
                                    "Aporrectodea trapezoides",
                                    "Octolasion cyaneum",
                                    "Eisenoides lonnbergi",
                                    "Lumbricus rubellus",
                                    "Lumbricus terrestris",
                                    "Amynthas hilgendorfi")))

write_rds(all_data_clean, "./Output/Data_clean/all_data_clean.rds")

DT::datatable(all_data_clean)
```

<br>

# SEAb
```{r SEAb}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(SIBER)
library(ellipse)
library(ggsci)
library(ggmcmc)


# Import files ------------------------------------------------------------
all_data_clean <- readRDS("./Output/Data_clean/all_data_clean.rds")


# Code starts here ---------------------------------------------------------

### Background-adjusted earthworm stable isotope values
adjusted_data <- all_data_clean %>%
  group_by(Dataset) %>%
  
  # Compute the differences between plot-level soil SI values and 
  # site-level (dataset-level) grand mean values (i.e., background references)
  mutate(d13C_soil_grand_mean = mean(d13C_soil_0_5),      
         d15N_soil_grand_mean = mean(d15N_soil_0_5)) %>%
  
  # Adjust the earthworm SI values by shifting back the differences between 
  # plot-level soil SI values and grand mean values 
  mutate(d13C_worm_adjusted = d13C_worm - (d13C_soil_0_5 - d13C_soil_grand_mean),
         d15N_worm_adjusted = d15N_worm - (d15N_soil_0_5 - d15N_soil_grand_mean)) %>%
  ungroup() %>%
  
  # Reorder the levels in column "Dataset" for plotting purpose
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))


### Bayesian SEA for each species
dataset_list <- unique(as.character(adjusted_data$Dataset))

SEAb_list <- lapply(dataset_list, function(dataset) {

  # Create SIBER object
  SIBER_data <- adjusted_data %>%
    filter(Dataset == dataset) %>%
    group_by(Species) %>%
    mutate(n.ind = n()) %>%
    filter(n.ind > 3) %>%
    select(
      iso1 = d13C_worm_adjusted,
      iso2 = d15N_worm_adjusted,
      group = Species
    ) %>%
    arrange(group) %>%
    ungroup() %>%
    mutate(group = plyr::mapvalues(
      group,
      unique(group),
      1:length(unique(group))
    )) %>%
    mutate(community = 1) %>%
    as.data.frame() %>%
    createSiberObject()

  # Get the species names
  Sp_names <- adjusted_data %>%
    filter(Dataset == dataset) %>%
    group_by(Species) %>%
    mutate(n.ind = n()) %>%
    filter(n.ind > 3) %>%
    .$Species %>%
    unique() %>%
    sort()

  # Bayesian model setup
  parms <- list()
  parms$n.iter <- 5000  # Number of iterations (here 5000 for test run; might need a longer chain for formal analysis!)
  parms$n.burnin <- 1000  # Burn-in
  parms$n.thin <- 10  # Thinning
  parms$n.chains <- 2  # Number of MCMC chains
  parms$save.output <- TRUE  # Save jags output for diagnostics
  parms$save.dir <- paste0(getwd(), "/", "Output/Jags")  # Folder to save jags output
  
  # Prior (the inverse Wishart prior)
  priors <- list()
  priors$R <- 1*diag(2)
  priors$k <- 2
  priors$tau.mu <- 0.001

  # Fit the model
  ellipses.posterior <- siberMVN(SIBER_data, parms, priors)
  SEA.B <- siberEllipses(ellipses.posterior) %>%
    as.data.frame() %>%
    `names<-`(Sp_names)
  
  # Model diagnostics
  all.files <- dir(parms$save.dir, full.names = TRUE)
  model.files <- all.files[grep("jags_output", all.files)]
  map(1:length(Sp_names), function(a){
    sp <- Sp_names[a]
    path <- paste0("./Output/Diagnostics/", dataset, "_", sp, ".pdf")
    load(model.files[a]) 
    S <- ggs(output)
    ggmcmc(S, plot = c("traceplot", "geweke"), param_page = 2, file = path)
  })
  
  # Compute standard ellipses data points from the posterior draws (for plotting)
  SEAb_points <- map(ellipses.posterior, function(x) {
    sigma <- matrix(apply(x[, 1:4], 2, mean), 2, 2) # Covariance matrix of the ellipses
    mu <- apply(x[, 5:6], 2, mean)  # Center of the ellipses
    sea <- ellipse(sigma, centre = mu, level = pchisq(1, 2), npoints = 100)  # Standard ellipses: pchisq(1, 2)
    return(sea)
  }) %>%
    `names<-`(Sp_names)
  
  SEAb_points <- data.frame(Species = Sp_names) %>%
    mutate(SEAb_points = map(SEAb_points, function(w){as.data.frame(w)}))
  
  # Summary statistics for the posterior draws
  SEAb_sum_stats <- SEA.B %>%
    pivot_longer(cols = everything(), names_to = "Species", values_to = "SEAb") %>%
    group_by(Species) %>%
    summarise(
      SEAb_mean = mean(SEAb),
      SEAb_sd = sd(SEAb),
      SEAb_mode = quantile(SEAb, 0.5),
      `SEAb_2.5%` = quantile(SEAb, 0.025),
      `SEAb_97.5%` = quantile(SEAb, 0.975)
    )

  # SEAb overlap
  SEAb_overlap <- data.frame(
    Sp1 = rep(Sp_names, each = length(Sp_names)),
    Sp2 = rep(Sp_names),
    Ellipse1 = paste(1, rep(1:length(Sp_names), each = length(Sp_names)), sep = "."),
    Ellipse2 = paste(1, rep(1:length(Sp_names)), sep = ".")
  ) %>%
    bind_cols(., map2(.x = .$Ellipse1, .y = .$Ellipse2, function(x, y) {
      bayesianOverlap(x, y,
        ellipses.posterior,
        draws = 100,  # Use first 100 posterior draws to calculate overlap
        p.interval = NULL,
        n = 100  # 100 points to form the ellipses
      ) %>%
        apply(., MARGIN = 2, FUN = function(z) mean(z)) %>%
        t() %>%
        as.data.frame() %>%
        `names<-`(c("area.1", "area.2", "overlap"))
    }) %>% bind_rows()) %>%
    select(-Ellipse1, -Ellipse2, -area.2) %>%
    rename(
      SEAb = area.1,
      Area = overlap
    ) %>%
    mutate(`Percent_overlap_%` = Area / SEAb * 100) %>%
    filter(Sp1 != Sp2) %>%
    rename(Species = Sp1) %>%
    group_by(Species) %>%
    rename(SEAb_overlap_with = Sp2) %>%
    mutate_if(is.numeric, round, digits = 3) %>%
    nest(SEAb_overlap = c(SEAb_overlap_with, Area, `Percent_overlap_%`)) %>%
    select(-SEAb)

  # Combine all the results
  SEAb_all <- SEAb_sum_stats %>%
    left_join(SEAb_overlap, by = "Species") %>%
    left_join(SEAb_points, by = "Species")

  return(SEAb_all)
  
}) %>% 
  `names<-`(dataset_list)


### Convert the list into a dataframe
SEAb_df <- SEAb_list %>% 
  bind_rows(.id = "Dataset") 

write_rds(SEAb_df, "./Output/Data_clean/SEAb.rds")

SEAb_df %>% select(-SEAb_points) %>% unnest(cols = c(SEAb_overlap)) %>% DT::datatable()

```

<br>

# Figures
## 1. Figure data preparation
```{r SEAb figure data preparation}
# Libraries ---------------------------------------------------------------
library(tidyverse)
library(magrittr)
library(ggsci)


# Import files ------------------------------------------------------------
all_data_clean <- readRDS("./Output/Data_clean/all_data_clean.rds")
SEAb_df <- readRDS("./Output/Data_clean/SEAb.rds")


# ggplot2 theme -----------------------------------------------------------
mytheme <- theme(
  axis.text.x = element_text(size = 12, color = "black"),
  axis.text.y = element_text(size = 12, color = "black"),
  axis.title.x = element_text(size = 15, margin = margin(t = 10)),
  axis.title.y = element_text(size = 15, margin = margin(r = 5)),
  plot.title = element_text(hjust = 0.5, size = 18),
  plot.margin = margin(0.2, 0.05, 0.05, 0.05, "null"),
  panel.background = element_rect(fill = "transparent"),
  plot.background = element_rect(colour = "transparent"),
  panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
  panel.grid.major.x = element_blank(),
  panel.grid.minor.x = element_blank(),
  panel.grid.major.y = element_blank(),
  panel.grid.minor.y = element_blank(),
  strip.background = element_blank(),
  strip.text = element_text(size = 12),
  legend.spacing.x = unit(0.1, "cm"),
  legend.spacing.y = unit(0.15, "cm"),
  legend.key.width = unit(1.2, "cm"),
  legend.key.size = unit(1, "line"),
  legend.key = element_blank(),
  legend.text = element_text(size = 7),
  legend.text.align = 0,
  legend.box.just = "center",
  legend.justification = c(0.5, 0.5),
  legend.title.align = 0.5,
  legend.background = element_rect(fill = "transparent", size = 0.5, linetype = "solid", colour = "transparent"))


# Code starts here ---------------------------------------------------------

### Background-adjusted earthworm stable isotope values
adjusted_data <- all_data_clean %>%
  group_by(Dataset) %>%
  
  # Compute the differences between plot-level soil SI values and 
  # site-level (dataset-level) grand mean values (i.e., background references)
  mutate(d13C_soil_grand_mean = mean(d13C_soil_0_5),      
         d15N_soil_grand_mean = mean(d15N_soil_0_5)) %>%
  
  # Adjust the earthworm SI values by shifting back the differences between 
  # plot-level soil SI values and grand mean values 
  mutate(d13C_worm_adjusted = d13C_worm - (d13C_soil_0_5 - d13C_soil_grand_mean),
         d15N_worm_adjusted = d15N_worm - (d15N_soil_0_5 - d15N_soil_grand_mean)) %>%
  ungroup() %>%
  
  # Reorder the levels in column "Dataset" for plotting purpose
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))
```

## 2. Biplots
```{r Biplot1, fig.width=11, fig.height=4.5}
### Stable isotope biplots
# BiodiversiTREE and BARC datasets
SEAb_points_df_1 <- SEAb_df %>% 
  filter(Dataset %in% c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC")) %>%
  select(Dataset, Species, SEAb_points) %>%
  unnest(cols = SEAb_points) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

label_df1 <- data.frame(Dataset = c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC"),
                        x = c(-32.5, -32.5, -32.5), 
                        y = c(13.25, 13.25, 13.25),
                        Label = c("(a)", "(b)", "(c)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

adjusted_data %>% 
  filter(Dataset %in% c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC")) %>%
  ggplot(aes(x = d13C_worm_adjusted, y = d15N_worm_adjusted)) +
  geom_point(aes(color = Species), size = 1.2, alpha = 0.7, stroke = 1) +
  labs(x = expression(paste(delta^{13}, "C (\u2030)", sep = "")), 
       y = expression(paste(delta^{15}, "N (\u2030)", sep = ""))) +
  geom_path(data = SEAb_points_df_1, aes(x = x, y = y, color = Species), size = 1) +
  facet_wrap(~Dataset, scales = "free_y") +
  geom_text(data = label_df1, aes(x = x, y = y, label = Label), size = 5) +
  scale_color_npg(name = NULL, 
                  label = c(expression(italic("Allolobophora chlorotica")),
                            expression(italic("Aporrectodea caliginosa")),
                            expression(italic("Aporrectodea trapezoides")),
                            expression(paste(italic("Diplocardia"), " sp.")),
                            expression(italic("Lumbricus friendi")),
                            expression(italic("Lumbricus rubellus")))) +
  coord_cartesian(xlim = c(-32, -13), ylim = c(0, 12), clip = "off") +
  scale_y_continuous(breaks = seq(1, 11, 2), labels = c("1.0", "3.0", "5.0", "7.0", "9.0", "11.0")) + 
  scale_x_continuous(breaks = seq(-30, -15, 5), labels = c("-30.0", "-25.0", "-20.0", "-15.0")) +
  guides(color = guide_legend(nrow = 2, byrow = T)) +
  mytheme + 
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 1.2)) 

ggsave("Output/Figures/SEAb_biplot1.tiff", width = 11, height = 4.5, dpi = 600)
```

```{r Biplot2, fig.width=8, fig.height=4.5}
# SERC dataset
SEAb_points_df_2 <- SEAb_df %>% 
  filter(Dataset %in% c("SERC_2011", "SERC_2013")) %>%
  select(Dataset, Species, SEAb_points) %>%
  unnest(cols = SEAb_points) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

label_df2 <- data.frame(Dataset = c("SERC_2011", "SERC_2013"),
                        x = c(-35.5, -35.5), 
                        y = c(7, 7),
                        Label = c("(a)", "(b)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

adjusted_data %>% 
  filter(Dataset %in% c("SERC_2011", "SERC_2013")) %>%
  ggplot(aes(x = d13C_worm_adjusted, y = d15N_worm_adjusted)) +
  geom_point(aes(color = Species), size = 1.2, alpha = 0.7, stroke = 1) +
  labs(x = expression(paste(delta^{13}, "C (\u2030)", sep = "")), 
       y = expression(paste(delta^{15}, "N (\u2030)", sep = ""))) +
  geom_path(data = SEAb_points_df_2, aes(x = x, y = y, color = Species), size = 1) +
  facet_wrap(~Dataset, scales = "free_y") +
  geom_text(data = label_df2, aes(x = x, y = y, label = Label), size = 5) +
  scale_color_brewer(name = NULL, palette = "Set1",
                     label = c(expression(italic("Amynthas hilgendorfi")),
                               expression(italic("Aporrectodea caliginosa")),
                               expression(italic("Eisenoides lonnbergi")),
                               expression(italic("Lumbricus rubellus")),
                               expression(italic("Lumbricus terrestris")),
                               expression(italic("Octolasion cyaneum")))) +
  coord_cartesian(xlim = c(-35, -20), ylim = c(-3, 6), clip = "off") +
  scale_y_continuous(breaks = seq(-3, 6, 1.5), labels = c("-3.0", "-1.5", "0", "1.5", "3.0", "4.5", "6.0")) + 
  scale_x_continuous(breaks = seq(-35, -20, 3), labels = c("-35.0", "-32.0", "-29.0", "-26.0", "-23.0", "-20.0")) +
  guides(color = guide_legend(nrow = 2, byrow = T)) +
  mytheme + 
  theme(legend.direction = "horizontal",
        legend.position = c(0.5, 1.2)) 

ggsave("Output/Figures/SEAb_biplot2.tiff", width = 8, height = 4.5, dpi = 600)
```

## 2. Dot charts of SEAbs of each species
```{r SEAb dotchart1, fig.width=11, fig.height=4}
### SEAb dot charts
# BiodiversiTREE and BARC datasets
label_df1 <- data.frame(Dataset = c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC"),
                        x = c(5.85, 5.85, 5.85), 
                        y = c(-1, -1, -1),
                        Label = c("(a)", "(b)", "(c)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

Sp_df1 <- adjusted_data %>% 
  filter(Dataset %in% c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC")) %>%
  .$Species %>% 
  unique() %>% 
  sort()

SEAb_df %>% 
  filter(Dataset %in% c("BiodiversiTREE_1", "BiodiversiTREE_2", "BARC")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T)) %>%
  mutate(Species = factor(Species, levels = Sp_df1, ordered = T)) %>%
  ggplot(aes(x = fct_rev(Species), y = SEAb_mean)) + 
  geom_pointrange(aes(ymin = `SEAb_2.5%`, ymax = `SEAb_97.5%`, color = Species)) +
  coord_flip(xlim = c(1, 5), ylim = c(0, 35), clip = "off") + 
  facet_wrap(~Dataset, scales = "free_x") +
  labs(x = NULL, y = expression(paste(SEA[b], " (", "\u2030"^2, ") ", "(Mean ± 95% CI)"))) +
  geom_text(data = label_df1, aes(x = x, y = y, label = Label), size = 5) +
  scale_x_discrete(drop = F,
                   limit = rev(Sp_df1[Sp_df1 != "Diplocardia sp."]),
                   label = rev(c(expression(italic("Allolobophora chlorotica")),
                                 expression(italic("Aporrectodea caliginosa")),
                                 expression(italic("Aporrectodea trapezoides")),
                                 expression(italic("Lumbricus friendi")),
                                 expression(italic("Lumbricus rubellus"))))) + 
  scale_color_npg(name = NULL, guide = F, drop = F) +
  scale_y_continuous(breaks = seq(0, 35, 5), labels = c("0", "5.0", "10.0", "15.0", "20.0", "25.0", "30.0", "35.0")) + 
  theme(axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 15, margin = margin(t = 10)),
        axis.title.y = element_text(size = 15, margin = margin(r = 8)),
        plot.title = element_text(hjust = 0.5, size = 18),
        plot.margin = rep(unit(0.05,"null"), 4),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(colour = "transparent"),
        strip.background = element_blank(),
        strip.text = element_text(size = 12),
        panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
        panel.grid.major.x = element_line(color = "grey90"),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey90"),
        panel.grid.minor.y = element_blank())
  
ggsave("Output/Figures/SEAb_dotchart1.tiff", width = 11, height = 4, dpi = 600)
```

```{r SEAb dotchart2, fig.width=8, fig.height=4}
# SERC dataset
label_df2 <- data.frame(Dataset = c("SERC_2011", "SERC_2013"),
                        x = c(5.85, 5.85), 
                        y = c(-0.3, -0.3),
                        Label = c("(a)", "(b)")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T))

Sp_df2 <- adjusted_data %>% 
  filter(Dataset %in% c("SERC_2011", "SERC_2013")) %>%
  .$Species %>% 
  unique() %>% 
  sort()

SEAb_df %>% 
  filter(Dataset %in% c("SERC_2011", "SERC_2013")) %>%
  mutate(Dataset = factor(Dataset, levels = unique(Dataset), ordered = T)) %>%
  mutate(Species = factor(Species, levels = Sp_df2, ordered = T)) %>%
  ggplot(aes(x = fct_rev(Species), y = SEAb_mean)) + 
  geom_pointrange(aes(ymin = `SEAb_2.5%`, ymax = `SEAb_97.5%`, color = Species)) +
  coord_flip(xlim = c(1, 5), ylim = c(0, 10), clip = "off") + 
  facet_wrap(~Dataset, scales = "free_x") +
  labs(x = NULL, y = expression(paste(SEA[b], " (", "\u2030"^2, ") ", "(Mean ± 95% CI)"))) +
  geom_text(data = label_df2, aes(x = x, y = y, label = Label), size = 5) +
  scale_x_discrete(drop = F,
                   limit = rev(Sp_df2[Sp_df2 != "Lumbricus terrestris"]),
                   label = rev(c(expression(italic("Amynthas hilgendorfi")),
                                 expression(italic("Aporrectodea caliginosa")),
                                 expression(italic("Eisenoides lonnbergi")),
                                 expression(italic("Lumbricus rubellus")),
                                 expression(italic("Octolasion cyaneum"))))) + 
  scale_color_brewer(name = NULL, guide = F, drop = F, palette = "Set1",
                     label = c(expression(italic("Amynthas hilgendorfi")),
                               expression(italic("Aporrectodea caliginosa")),
                               expression(italic("Eisenoides lonnbergi")),
                               expression(italic("Lumbricus rubellus")),
                               expression(italic("Octolasion cyaneum")))) +
  scale_y_continuous(breaks = seq(0, 10, 2.5), labels = c("0", "2.5", "5.0", "7.5", "10.0")) + 
  theme(axis.text.x = element_text(size = 12, color = "black"),
        axis.text.y = element_text(size = 10, color = "black"),
        axis.title.x = element_text(size = 15, margin = margin(t = 10)),
        axis.title.y = element_text(size = 15, margin = margin(r = 8)),
        plot.title = element_text(hjust = 0.5, size = 18),
        plot.margin = rep(unit(0.05,"null"), 4),
        panel.background = element_rect(fill = "transparent"),
        plot.background = element_rect(colour = "transparent"),
        strip.background = element_blank(),
        strip.text = element_text(size = 12),
        panel.border = element_rect(colour = "black", fill = NA, size = 0.5),
        panel.grid.major.x = element_line(color = "grey90"),
        panel.grid.minor.x = element_blank(),
        panel.grid.major.y = element_line(color = "grey90"),
        panel.grid.minor.y = element_blank())

ggsave("Output/Figures/SEAb_dotchart2.tiff", width = 8, height = 4, dpi = 600)
```

## 3. Heatmap of percent overlap in SEAb between species (BiodiversiTREE_1)
```{r heatmap, fig.width=8, fig.height=5.5}
### SEAb percent overlap heatmap
SEAb_df %>% filter(Dataset == "BiodiversiTREE_1") %>%
  select(1:3, SEAb_overlap) %>%
  unnest(cols = SEAb_overlap) %>%
  ggplot() +
  geom_tile(aes(x = Species, y = fct_rev(SEAb_overlap_with), fill = `Percent_overlap_%`)) + 
  scale_x_discrete(position = "top", expand = c(0, 0),
                   label = c(expression(italic("Allolobophora \n   chlorotica")),
                                 expression(italic("Aporrectodea \n   caliginosa")),
                                 expression(italic("Aporrectodea \n  trapezoides")),
                                 expression(italic("Lumbricus \n   friendi")),
                                 expression(italic("Lumbricus \n  rubellus")))) +
  scale_y_discrete(expand = c(0, 0), 
                   label = rev(c(expression(italic("Allolobophora \n   chlorotica")),
                             expression(italic("Aporrectodea \n   caliginosa")),
                             expression(italic("Aporrectodea \n  trapezoides")),
                             expression(italic("Lumbricus \n   friendi")),
                             expression(italic("Lumbricus \n  rubellus"))))) +
  scale_fill_continuous(trans = 'reverse', name = "Percent (%)") + 
  guides(fill = guide_colorbar(reverse = T)) + 
  labs(x = expression(paste(SEA[b], " (", "\u2030"^2, ") of")), 
       y = "Overlapping with") +
  mytheme + 
  theme(axis.title.x.top = element_text(size = 15, margin = margin(b = 15)),
        axis.title.y.left = element_text(size = 17, margin = margin(r = 8)),
        axis.text.x = element_text(size = 10, color = "black"),
        axis.text.y = element_text(size = 10, color = "black", vjust = 1),
        plot.margin = margin(0.05, 0.05, 0.05, 0.05, "null"),
        legend.key.width = unit(0.7, "cm"),
        legend.text = element_text(size = 8))

ggsave("Output/Figures/Overlap.tiff", width = 8, height = 5.5, dpi = 600)

```





